export const COUNTRIES = [
    {code: 'AR', name: 'Argentina', flag: '🇦🇷'},
    {code: 'BO', name: 'Bolivia', flag: '🇧🇴'},
    {code: 'BR', name: 'Brazil', flag: '🇧🇷'},
    {code: 'CA', name: 'Canada', flag: '🇨🇦'},
    {code: 'CL', name: 'Chile', flag: '🇨🇱'},
    {code: 'CO', name: 'Colombia', flag: '🇨🇴'},
    {code: 'CR', name: 'Costa Rica', flag: '🇨🇷'},
    {code: 'CU', name: 'Cuba', flag: '🇨🇺'},
    {code: 'DO', name: 'Dominican Republic', flag: '🇩🇴'},
    {code: 'EC', name: 'Ecuador', flag: '🇪🇨'},
    {code: 'SV', name: 'El Salvador', flag: '🇸🇻'},
    {code: 'ES', name: 'Spain', flag: '🇪🇸'},
    {code: 'GT', name: 'Guatemala', flag: '🇬🇹'},
    {code: 'HT', name: 'Haiti', flag: '🇭🇹'},
    {code: 'HN', name: 'Honduras', flag: '🇭🇳'},
    {code: 'JM', name: 'Jamaica', flag: '🇯🇲'},
    {code: 'MX', name: 'Mexico', flag: '🇲🇽'},
    {code: 'NI', name: 'Nicaragua', flag: '🇳🇮'},
    {code: 'PA', name: 'Panama', flag: '🇵🇦'},
    {code: 'PY', name: 'Paraguay', flag: '🇵🇾'},
    {code: 'PE', name: 'Peru', flag: '🇵🇪'},
    {code: 'PR', name: 'Puerto Rico', flag: '🇵🇷'},
    {code: 'UY', name: 'Uruguay', flag: '🇺🇾'},
    {code: 'US', name: 'United States', flag: '🇺🇸'},
    {code: 'VE', name: 'Venezuela', flag: '🇻🇪'},
    {code: 'AT', name: 'Austria', flag: '🇦🇹'},
    {code: 'AU', name: 'Australia', flag: '🇦🇺'},
    {code: 'BE', name: 'Belgium', flag: '🇧🇪'},
    {code: 'BG', name: 'Bulgaria', flag: '🇧🇬'},
    {code: 'BY', name: 'Belarus', flag: '🇧🇾'},
    {code: 'CN', name: 'China', flag: '🇨🇳'},
    {code: 'DE', name: 'Germany', flag: '🇩🇪'},
    {code: 'DK', name: 'Denmark', flag: '🇩🇰'},
    {code: 'EE', name: 'Estonia', flag: '🇪🇪'},
    {code: 'FI', name: 'Finland', flag: '🇫🇮'},
    {code: 'FR', name: 'France', flag: '🇫🇷'},
    {code: 'GB', name: 'United Kingdom', flag: '🇬🇧'},
    {code: 'GR', name: 'Greece', flag: '🇬🇷'},
    {code: 'HR', name: 'Croatia', flag: '🇭🇷'},
    {code: 'HU', name: 'Hungary', flag: '🇭🇺'},
    {code: 'ID', name: 'Indonesia', flag: '🇮🇩'},
    {code: 'IE', name: 'Ireland', flag: '🇮🇪'},
    {code: 'IN', name: 'India', flag: '🇮🇳'},
    {code: 'IQ', name: 'Iraq', flag: '🇮🇶'},
    {code: 'IS', name: 'Iceland', flag: '🇮🇸'},
    {code: 'IT', name: 'Italy', flag: '🇮🇹'},
    {code: 'JP', name: 'Japan', flag: '🇯🇵'},
    {code: 'KE', name: 'Kenya', flag: '🇰🇪'},
    {code: 'KR', name: 'South Korea', flag: '🇰🇷'},
    {code: 'KW', name: 'Kuwait', flag: '🇰🇼'},
    {code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿'},
    {code: 'LB', name: 'Lebanon', flag: '🇱🇧'},
    {code: 'LK', name: 'Sri Lanka', flag: '🇱🇰'},
    {code: 'LT', name: 'Lithuania', flag: '🇱🇹'},
    {code: 'LU', name: 'Luxembourg', flag: '🇱🇺'},
    {code: 'LV', name: 'Latvia', flag: '🇱🇻'},
    {code: 'LY', name: 'Libya', flag: '🇱🇾'},
    {code: 'MA', name: 'Morocco', flag: '🇲🇦'},
    {code: 'MD', name: 'Moldova', flag: '🇲🇩'},
    {code: 'ME', name: 'Montenegro', flag: '🇲🇪'},
    {code: 'MK', name: 'North Macedonia', flag: '🇲🇰'},
    {code: 'MN', name: 'Mongolia', flag: '🇲🇳'},
    {code: 'MO', name: 'Macau', flag: '🇲🇴'},
    {code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵'},
    {code: 'MQ', name: 'Martinique', flag: '🇲🇶'},
    {code: 'MR', name: 'Mauritania', flag: '🇲🇷'},
    {code: 'MU', name: 'Mauritius', flag: '🇲🇺'},
    {code: 'MV', name: 'Maldives', flag: '🇲🇻'},
    {code: 'MW', name: 'Malawi', flag: '🇲🇼'},
    {code: 'MX', name: 'Mexico', flag: '🇲🇽'},
    {code: 'MY', name: 'Malaysia', flag: '🇲🇾'},
    {code: 'MZ', name: 'Mozambique', flag: '🇲🇿'},
    {code: 'NA', name: 'Namibia', flag: '🇳🇦'},
    {code: 'NE', name: 'Niger', flag: '🇳🇪'},
    {code: 'NG', name: 'Nigeria', flag: '🇳🇬'},
    {code: 'NI', name: 'Nicaragua', flag: '🇳🇮'},
    {code: 'NL', name: 'Netherlands', flag: '🇳🇱'},
    {code: 'NO', name: 'Norway', flag: '🇳🇴'},
    {code: 'NP', name: 'Nepal', flag: '🇳🇵'},
    {code: 'NR', name: 'Nauru', flag: '🇳🇷'},
    {code: 'NZ', name: 'New Zealand', flag: '🇳🇿'},
    {code: 'OM', name: 'Oman', flag: '🇴🇲'},
    {code: 'PA', name: 'Panama', flag: '🇵🇦'},
    {code: 'PE', name: 'Peru', flag: '🇵🇪'},
    {code: 'PF', name: 'French Polynesia', flag: '🇵🇫'},
    {code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬'},
    {code: 'PH', name: 'Philippines', flag: '🇵🇭'},
    {code: 'PK', name: 'Pakistan', flag: '🇵🇰'},
    {code: 'PL', name: 'Poland', flag: '🇵🇱'},
    {code: 'PR', name: 'Puerto Rico', flag: '🇵🇷'},
    {code: 'PT', name: 'Portugal', flag: '🇵🇹'},
    {code: 'PY', name: 'Paraguay', flag: '🇵🇾'},
    {code: 'QA', name: 'Qatar', flag: '🇶🇦'},
    {code: 'RE', name: 'Réunion', flag: '🇷🇪'},
    {code: 'RO', name: 'Romania', flag: '🇷🇴'},
    {code: 'RS', name: 'Serbia', flag: '🇷🇸'},
    {code: 'RU', name: 'Russia', flag: '🇷🇺'},
    {code: 'RW', name: 'Rwanda', flag: '🇷🇼'},
    {code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦'},
    {code: 'SB', name: 'Solomon Islands', flag: '🇸🇧'},
    {code: 'SC', name: 'Seychelles', flag: '🇸🇨'},
    {code: 'SD', name: 'Sudan', flag: '🇸🇩'},
    {code: 'SE', name: 'Sweden', flag: '🇸🇪'},
    {code: 'SG', name: 'Singapore', flag: '🇸🇬'},
    {code: 'SH', name: 'Saint Helena', flag: '🇸🇭'},
    {code: 'SI', name: 'Slovenia', flag: '🇸🇮'},
    {code: 'SK', name: 'Slovakia', flag: '🇸🇰'},
    {code: 'SL', name: 'Sierra Leone', flag: '🇸🇱'},
    {code: 'SM', name: 'San Marino', flag: '🇸🇲'},
    {code: 'SN', name: 'Senegal', flag: '🇸🇳'},
    {code: 'SO', name: 'Somalia', flag: '🇸🇴'},
    {code: 'SR', name: 'Suriname', flag: '🇸🇷'},
    {code: 'SS', name: 'South Sudan', flag: '🇸🇸'},
    {code: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹'},
    {code: 'SV', name: 'El Salvador', flag: '🇸🇻'},
    {code: 'SY', name: 'Syria', flag: '🇸🇾'},
    {code: 'SZ', name: 'Eswatini', flag: '🇸🇿'},
    {code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨'},
    {code: 'TD', name: 'Chad', flag: '🇹🇩'},
    {code: 'TF', name: 'French Southern Territories', flag: '🇹🇫'},
    {code: 'TG', name: 'Togo', flag: '🇹🇬'},
    {code: 'TH', name: 'Thailand', flag: '🇹🇭'},
    {code: 'TJ', name: 'Tajikistan', flag: '🇹🇯'},
    {code: 'TK', name: 'Tokelau', flag: '🇹🇰'},
    {code: 'TL', name: 'Timor-Leste', flag: '🇹🇱'},
    {code: 'TM', name: 'Turkmenistan', flag: '🇹🇲'},
    {code: 'TN', name: 'Tunisia', flag: '🇹🇳'},
    {code: 'TO', name: 'Tonga', flag: '🇹🇴'},
    {code: 'TR', name: 'Turkey', flag: '🇹🇷'},
    {code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹'},
    {code: 'TV', name: 'Tuvalu', flag: '🇹🇻'},
    {code: 'TZ', name: 'Tanzania', flag: '🇹🇿'},
    {code: 'UA', name: 'Ukraine', flag: '🇺🇦'},
    {code: 'UG', name: 'Uganda', flag: '🇺🇬'},
    {code: 'US', name: 'United States', flag: '🇺🇸'},
    {code: 'UY', name: 'Uruguay', flag: '🇺🇾'},
    {code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿'},
    {code: 'VA', name: 'Vatican City', flag: '🇻🇦'},
    {code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨'},
    {code: 'VE', name: 'Venezuela', flag: '🇻🇪'},
    {code: 'VN', name: 'Vietnam', flag: '🇻🇳'},
    {code: 'VU', name: 'Vanuatu', flag: '🇻🇺'},
    {code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫'},
    {code: 'WS', name: 'Samoa', flag: '🇼🇸'},
    {code: 'YE', name: 'Yemen', flag: '🇾🇪'},
    {code: 'ZA', name: 'South Africa', flag: '🇿🇦'},
    {code: 'ZM', name: 'Zambia', flag: '🇿🇲'},
    {code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼'},
] as const;